<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>实例方法then链式调用的实现</title>
</head>
<body>
    <script>
        // 用Symbol定义三种状态，防止外界改变状态。
        const Pending = Symbol("Pending"); // 进行中
        const Fulfilled = Symbol("Fulfilled"); // 已成功
        const Rejected = Symbol("Rejected"); // 已失败
        const handleValue = (promise, x, resolve, reject) => {
            // 循环引用，自己等待自己完成，会出错，用reject传递出错误原因
            if (promise === x) {
                return reject(new TypeError("检测到Promise的链式循环饮用"));
            }
            // 确保只传递出去一次值
            let once = false;
            if ((x !== null && typeof x === "object") || typeof x === "function") {
                let then = x.then;
                // 判断x是不是Promise
                if (typeof then === "function") {
                    // x是Promise，调用then实例方法处理x的执行结果。
                    then.call(x, y => {
                        if (once) return;
                        once = true;
                        // 防止Promise中Promise执行成功后又传递一个Promise过来，
                        // 要做递归解析。
                        handleValue(promise, y, resolve, reject);
                    }, r => {
                        if (once) return;
                        once = true;
                        reject(r);
                    })
                } else {
                    // x是普通对象，直接调用resolve(x)
                    resolve(x);
                }
            } else {
                // x是原始值，直接调用resolve(x)
                resolve(x);
            }
        }
        class Promise {
            constructor (executor) {
                this.status = Pending; // 存储Promise的状态
                this.value = undefined; // 存储executor函数中业务代码执行成功的结果
                this.reason = undefined; // 存储executor函数中业务代码执行失败的原因
                this.onFulfilled = []; // executor函数中业务代码执行成功回调函数的集合
                this.onRejected = []; // executor函数中业务代码执行失败回调函数的集合
                const resolve = value => {
                    // 只有当状态为Pending才会改变，来保证一旦状态改变就不会再变。
                    if (this.status === Pending) {
                        this.status = Fulfilled;
                        this.value = value;
                        // 依次调用成功回调函数
                        this.onFulfilled.forEach(fn => fn());
                    }
                };
                const reject = reason => {
                    // 只有当状态为Pending才会改变，来保证一旦状态改变就不会再变。
                    if (this.status === Pending) {
                        this.status = Rejected;
                        this.reason = reason;
                        // 依次调用失败回调函数
                        this.onRejected.forEach(fn => fn());
                    }
                }
                executor(resolve, reject);
            }
            then (onFulfilled, onRejected) {
                const promise = new Promise((resolve, reject) => {
                    if (this.status === Fulfilled) {
                        if (onFulfilled && typeof onFulfilled === "function") {
                            setTimeout(() => {
                                let x = onFulfilled(this.value);
                                handleValue(promise, x, resolve, reject);
                            }, 0)
                        }
                    }
                    if (this.status === Rejected) {
                        if (onRejected && typeof onRejected === "function") {
                            setTimeout(() => {
                                let x = onRejected(this.reason);
                                handleValue(promise, x, resolve, reject);
                            }, 0)
                        }
                    }
                    if (this.status === Pending) {
                        if (onFulfilled && typeof onFulfilled === "function") {
                            this.onFulfilled.push(() => {
                                setTimeout(() => {
                                    let x = onFulfilled(this.value);
                                    handleValue(promise, x, resolve, reject);
                                }, 0)
                            })
                        }
                        if (onRejected && typeof onRejected === "function") {
                            this.onRejected.push(() => {
                                setTimeout(() => {
                                    let x = onRejected(this.reason);
                                    handleValue(promise, x, resolve, reject);
                                }, 0)
                            })
                        }
                    }
                })
                return promise;
            }
        }
    </script>
    <script>
        let p = new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("executor");
                resolve("执行成功");
                // reject("执行失败");
            }, 1000)
        }).then(val => {
            console.log(val);
            // return "I am then11";
            const p1 = new Promise((resolve, reject) => {
                // const p2 = new Promise((resolve, reject) => {
                //     resolve("I am p2 resolve");
                // });
                // resolve(p2);
                resolve("I am p1 resolve");
            });
            return p1;
        }, res => {
            console.log(res);
            return "I am then12";
        }).then(val => {
            console.log(val);
            return `${val}1`;
        }, res => {
            console.log(res);
            return `${res}2`;
        }).then(val => {
            console.log(val);
            return `${val}1`;
        }, res => {
            console.log(res);
            return `${res}2`;
        }).then(val => {
            console.log(val);
            return `${val}1`;
        }, res => {
            console.log(res);
            return `${res}2`;
        })
    </script>
</body>
</html>